apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentication-service
  name: authentication-service
  namespace: o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - image: paulofponciano/sample-app-ms-o11y-k8s:authentication-service
        name: authentication-service
        ports:
        - containerPort: 5000
        resources: # Verify the amount of requests
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OTLP
          value: "otel-collector.o11y.svc.cluster.local"
        - name: RECOMMEND
          value: "recommendation-service.o11y.svc.cluster.local"
        - name: LOGS
          value: "analytics-service.o11y.svc.cluster.local" # Analytics Service
        
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: o11y
  annotations:
    service.cilium.io/lb-l7: enabled
    service.cilium.io/lb-l7-algorithm: round_robin
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: authentication-service