prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector:
      any: true
    podMonitorSelector: {}
    ruleNamespaceSelector:
      any: true
    ruleSelector: {}
    serviceMonitorNamespaceSelector:
      any: true
    serviceMonitorSelector: {}

prometheusOperator:
  enabled: true
  namespaces: ''
  denyNamespaces: ''
  prometheusInstanceNamespaces: ''
  alertmanagerInstanceNamespaces: ''
  thanosRulerInstanceNamespaces: ''

grafana:
  enabled: true