---
##################################################################################################
# Client Service - React
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: client-react
  namespace: o11y
  annotations:
    service.cilium.io/lb-l7: enabled
    service.cilium.io/lb-l7-algorithm: round_robin
  labels:
    app: client-react
    service: client-react
spec:
  ports:
  - port: 5000
    name: http
  selector:
    app: client-react
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-react
  namespace: o11y
  labels:
    app: client-react
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-react
      version: v1
  template:
    metadata:
      labels:
        app: client-react
        version: v1
    spec:
      containers:
      - name: client-react
        image: paulofponciano/sample-app-ms-o11y-k8s:client-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        env:
        - name: OTLP
          value: "otel-collector.o11y.svc.cluster.local"
        - name: RECOMMEND
          value: "recommendation-service.o11y.svc.cluster.local"
        - name: LOGS
          value: "analytics-service.o11y.svc.cluster.local" # Analytics Service
        - name: ORDER
          value: "order-service.o11y.svc.cluster.local"
        - name: INVENTORY
          value: "inventory-service.o11y.svc.cluster.local"
        - name: PAYMENT
          value: "payment-service.o11y.svc.cluster.local"
        - name: AUTH
          value: "authentication-service.o11y.svc.cluster.local"
        - name: MYSQL_HOST
          value: "mysql.o11y.svc.cluster.local"
        - name: MYSQL_PORT
          value: "3306"
      volumes:
      - name: tmp
        emptyDir: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-react0ingress
  namespace: o11y
spec:
  ingressClassName: cilium
  rules:
  - host: ms.pauloponciano.digital
    http:
      paths:
      - backend:
          service:
            name: client-react
            port:
              number: 5000
        path: /
        pathType: Prefix